language: node_js

node_js:
  - "lts/*"

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    local-dir: dist
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master